alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

alias alert='notify-send --urgency=low -i "$([$? =0 ) && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias cd..='cd ..'
alias cdgh='cd $HOME/github'

alias cbail='cmake build . && make all && sudo make install && sudo ldconfig'

export EDITOR='nvim'
alias vim='nvim'

